DROP TABLE "LIKED";
DROP TABLE "REVIEW";
DROP TABLE "PREFERENCE";
DROP TABLE "GENRE_LIST";
DROP TABLE "ACTOR_LIST";
DROP TABLE "DIRECTED_MOVIE";
DROP TABLE "ACTOR";
DROP TABLE "DIRECTOR";
DROP TABLE "GENRE";
DROP TABLE "MEMBER";
DROP TABLE "AGE_GROUP";
DROP TABLE "MOVIE";

CREATE TABLE "MOVIE" (
	"MOVIE_ID"	NUMBER		NOT NULL,
	"TITLE"	VARCHAR2(300)		NOT NULL,
	"OPENING_YEAR"	NUMBER		NOT NULL,
	"POSTER"	VARCHAR2(200)		NOT NULL
);

CREATE TABLE "AGE_GROUP" (
	"AGE_GROUP"	NUMBER		NOT NULL,
	"AGE_TITLE"	VARCHAR2(30)		NOT NULL
);

CREATE TABLE "MEMBER" (
	"EMAIL"	VARCHAR2(50)		NOT NULL,
	"PASSWORD"	VARCHAR2(20)		NOT NULL,
	"NICKNAME"	VARCHAR2(15)		NOT NULL,
	"AGE_GROUP"	NUMBER		NOT NULL
);

CREATE TABLE "GENRE" (
	"GENRE_ID"	NUMBER		NOT NULL,
	"GENRE_TITLE"	VARCHAR2(15)		NOT NULL
);

CREATE TABLE "DIRECTOR" (
	"DIRECTOR_ID"	NUMBER		NOT NULL,
	"DIRECTOR_NAME"	VARCHAR2(300)		NOT NULL
);

CREATE TABLE "ACTOR" (
	"ACTOR_ID"	NUMBER		NOT NULL,
	"ACTOR_NAME"	VARCHAR2(300)		NOT NULL
);

CREATE TABLE "DIRECTED_MOVIE" (
	"DIRECTOR_ID"	NUMBER		NOT NULL,
	"MOVIE_ID"	NUMBER		NOT NULL
);

CREATE TABLE "ACTOR_LIST" (
	"ACTOR_ID"	NUMBER		NOT NULL,
	"MOVIE_ID"	NUMBER		NOT NULL
);

CREATE TABLE "GENRE_LIST" (
	"GENRE_ID"	NUMBER		NOT NULL,
	"MOVIE_ID"	NUMBER		NOT NULL
);

CREATE TABLE "PREFERENCE" (
	"EMAIL"	VARCHAR2(50)		NOT NULL,
	"GENRE_ID"	NUMBER		NOT NULL
);

CREATE TABLE "REVIEW" (
	"REVIEW_ID"	INT		NOT NULL,
	"MOVIE_ID"	NUMBER		NOT NULL,
	"EMAIL"	VARCHAR2(50)		NOT NULL,
	"CONTENT"	VARCHAR2(200)		NOT NULL
);

CREATE TABLE "LIKED" (
	"REVIEW_ID"	INT		NOT NULL,
	"EMAIL"	VARCHAR2(50)		NOT NULL
);

ALTER TABLE "MOVIE" ADD CONSTRAINT "PK_MOVIE" PRIMARY KEY (
	"MOVIE_ID"
);

ALTER TABLE "ACTOR" ADD CONSTRAINT "PK_ACTOR" PRIMARY KEY (
	"ACTOR_ID"
);

ALTER TABLE "DIRECTOR" ADD CONSTRAINT "PK_DIRECTOR" PRIMARY KEY (
	"DIRECTOR_ID"
);

ALTER TABLE "GENRE_LIST" ADD CONSTRAINT "PK_GENRE_LIST" PRIMARY KEY (
	"GENRE_ID",
	"MOVIE_ID"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"EMAIL"
);

ALTER TABLE "REVIEW" ADD CONSTRAINT "PK_REVIEW" PRIMARY KEY (
	"REVIEW_ID"
);

ALTER TABLE "PREFERENCE" ADD CONSTRAINT "PK_PREFERENCE" PRIMARY KEY (
	"EMAIL",
	"GENRE_ID"
);

ALTER TABLE "DIRECTED_MOVIE" ADD CONSTRAINT "PK_DIRECTED_MOVIE" PRIMARY KEY (
	"DIRECTOR_ID",
	"MOVIE_ID"
);

ALTER TABLE "ACTOR_LIST" ADD CONSTRAINT "PK_ACTOR_LIST" PRIMARY KEY (
	"ACTOR_ID",
	"MOVIE_ID"
);

ALTER TABLE "AGE_GROUP" ADD CONSTRAINT "PK_AGE_GROUP" PRIMARY KEY (
	"AGE_GROUP"
);

ALTER TABLE "GENRE" ADD CONSTRAINT "PK_GENRE" PRIMARY KEY (
	"GENRE_ID"
);

ALTER TABLE "GENRE_LIST" ADD CONSTRAINT "FK_GENRE_TO_GENRE_LIST_1" FOREIGN KEY (
	"GENRE_ID"
)
REFERENCES "GENRE" (
	"GENRE_ID"
);

ALTER TABLE "GENRE_LIST" ADD CONSTRAINT "FK_MOVIE_TO_GENRE_LIST_1" FOREIGN KEY (
	"MOVIE_ID"
)
REFERENCES "MOVIE" (
	"MOVIE_ID"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "FK_AGE_GROUP_TO_MEMBER_1" FOREIGN KEY (
	"AGE_GROUP"
)
REFERENCES "AGE_GROUP" (
	"AGE_GROUP"
);

ALTER TABLE "REVIEW" ADD CONSTRAINT "FK_MOVIE_TO_REVIEW_1" FOREIGN KEY (
	"MOVIE_ID"
)
REFERENCES "MOVIE" (
	"MOVIE_ID"
);

ALTER TABLE "REVIEW" ADD CONSTRAINT "FK_MEMBER_TO_REVIEW_1" FOREIGN KEY (
	"EMAIL"
)
REFERENCES "MEMBER" (
	"EMAIL"
);

ALTER TABLE "LIKED" ADD CONSTRAINT "FK_REVIEW_TO_LIKE_1" FOREIGN KEY (
	"REVIEW_ID"
)
REFERENCES "REVIEW" (
	"REVIEW_ID"
);

ALTER TABLE "LIKED" ADD CONSTRAINT "FK_MEMBER_TO_LIKE_1" FOREIGN KEY (
	"EMAIL"
)
REFERENCES "MEMBER" (
	"EMAIL"
);

ALTER TABLE "PREFERENCE" ADD CONSTRAINT "FK_MEMBER_TO_PREFERENCE_1" FOREIGN KEY (
	"EMAIL"
)
REFERENCES "MEMBER" (
	"EMAIL"
);

ALTER TABLE "PREFERENCE" ADD CONSTRAINT "FK_GENRE_TO_PREFERENCE_1" FOREIGN KEY (
	"GENRE_ID"
)
REFERENCES "GENRE" (
	"GENRE_ID"
);

ALTER TABLE "DIRECTED_MOVIE" ADD CONSTRAINT "FK_DIRECTOR_TO_DIRECTED_MOVIE_1" FOREIGN KEY (
	"DIRECTOR_ID"
)
REFERENCES "DIRECTOR" (
	"DIRECTOR_ID"
);

ALTER TABLE "DIRECTED_MOVIE" ADD CONSTRAINT "FK_MOVIE_TO_DIRECTED_MOVIE_1" FOREIGN KEY (
	"MOVIE_ID"
)
REFERENCES "MOVIE" (
	"MOVIE_ID"
);

ALTER TABLE "ACTOR_LIST" ADD CONSTRAINT "FK_ACTOR_TO_ACTOR_LIST_1" FOREIGN KEY (
	"ACTOR_ID"
)
REFERENCES "ACTOR" (
	"ACTOR_ID"
);

ALTER TABLE "ACTOR_LIST" ADD CONSTRAINT "FK_MOVIE_TO_ACTOR_LIST_1" FOREIGN KEY (
	"MOVIE_ID"
)
REFERENCES "MOVIE" (
	"MOVIE_ID"
);

--MOVIE
INSERT INTO MOVIE (MOVIE_ID, TITLE, OPENING_YEAR, POSTER)
VALUES (200101, '듄', 2021, '듄포스터');

INSERT INTO MOVIE (MOVIE_ID, TITLE, OPENING_YEAR, POSTER)
VALUES (200102, '엘리멘탈', 2021, '엘리멘탈포스터');

--AGE_GROUP
INSERT INTO AGE_GROUP (AGE_GROUP, AGE_TITLE)
VALUES (10, '10대');

--MEMBER
INSERT INTO MEMBER (EMAIL, PASSWORD, NICKNAME, AGE_GROUP)
VALUES ('ABC@NAVER.COM', '1234567!', '영화좋아', 10);

--GENRE
INSERT INTO GENRE (GENRE_ID, GENRE_TITLE)
VALUES (200201, 'SF');

--DIRECTOR
INSERT INTO DIRECTOR (DIRECTOR_ID, DIRECTOR_NAME)
VALUES (200301, '드니 빌뇌브');

--ACTOR
INSERT INTO ACTOR (ACTOR_ID, ACTOR_NAME)
VALUES (200401, '티모시 샬라메');

--DIRECTED_MOVIE --드니 감독의 감독번호, 드니 감독이 한 영화 번호
INSERT INTO DIRECTED_MOVIE (DIRECTOR_ID, MOVIE_ID)
VALUES (200301, 200101);

--ACTOR_LIST
INSERT INTO ACTOR_LIST (ACTOR_ID, MOVIE_ID)
VALUES (200401, 200101);   
    --티모시의 번호와 티모시가 출연한 영화 번호

--GENRE_LIST
INSERT INTO GENRE_LIST (GENRE_ID, MOVIE_ID)
VALUES (200201, 200101);
    --장르번호와 영화번호

--PREFERENCE
INSERT INTO PREFERENCE (EMAIL, GENRE_ID)
VALUES ('ABC@NAVER.COM', 200201);
    --이메일이랑 장르번호

--REVIEW
INSERT INTO REVIEW (REVIEW_ID, MOVIE_ID, EMAIL, CONTENT)
VALUES (1, 200101, 'ABC@NAVER.COM', '정말재밌어요');
    --댓글번호

--LIKE
INSERT INTO LIKED (REVIEW_ID, EMAIL)
VALUES (1, 'ABC@NAVER.COM');

commit;