DROP TABLE "LIKE";
DROP TABLE "REVIEW";
DROP TABLE "PREFERENCE";
DROP TABLE "GENRE_LIST";
DROP TABLE "ACTOR_LIST";
DROP TABLE "DIRECTED_MOVIE";
DROP TABLE "ACTOR";
DROP TABLE "DIRECTOR";
DROP TABLE "GENRE";
DROP TABLE "MEMBER";
DROP TABLE "AGE_GROUP";
DROP TABLE "MOVIE";

CREATE TABLE "MOVIE" (
	"MOVIE_ID"	NUMBER		NOT NULL,
	"TITLE"	VARCHAR2(300)		NOT NULL,
	"OPENING_YEAR"	NUMBER		NOT NULL,
	"POSTER"	VARCHAR2(200)		NOT NULL
);

CREATE TABLE "AGE_GROUP" (
	"AGE_GROUP"	NUMBER		NOT NULL,
	"AGE_TITLE"	VARCHAR2(30)		NOT NULL
);

CREATE TABLE "MEMBER" (
	"EMAIL"	VARCHAR2(50)		NOT NULL,
	"PASSWORD"	VARCHAR2(20)		NOT NULL,
	"NICKNAME"	VARCHAR2(10)		NOT NULL,
	"AGE_GROUP"	NUMBER		NOT NULL
);

CREATE TABLE "GENRE" (
	"GENRE_ID"	NUMBER		NOT NULL,
	"GENRE_TITLE"	VARCHAR2(15)		NOT NULL
);

CREATE TABLE "DIRECTOR" (
	"DIRECTOR_ID"	NUMBER		NOT NULL,
	"DIRECTOR_NAME"	VARCHAR2(300)		NOT NULL
);

CREATE TABLE "ACTOR" (
	"ACTOR_ID"	NUMBER		NOT NULL,
	"ACTOR_NAME"	VARCHAR2(300)		NOT NULL
);

CREATE TABLE "DIRECTED_MOVIE" (
	"DIRECTOR_ID"	NUMBER		NOT NULL,
	"MOVIE_ID"	NUMBER		NOT NULL
);

CREATE TABLE "ACTOR_LIST" (
	"ACTOR_ID"	NUMBER		NOT NULL,
	"MOVIE_CD"	NUMBER		NOT NULL
);

CREATE TABLE "GENRE_LIST" (
	"GENRE_ID"	NUMBER		NOT NULL,
	"MOVIE_ID"	NUMBER		NOT NULL
);

CREATE TABLE "PREFERENCE" (
	"EMAIL"	VARCHAR2(50)		NOT NULL,
	"GENRE_ID"	NUMBER		NOT NULL
);

CREATE TABLE "REVIEW" (
	"REVIEW_ID"	INT		NOT NULL,
	"MOVIE_CD"	NUMBER		NOT NULL,
	"EMAIL"	VARCHAR2(50)		NOT NULL,
	"CONTENT"	VARCHAR2(200)		NOT NULL
);

CREATE TABLE "LIKE" (
	"REVIEW_ID"	INT		NOT NULL,
	"EMAIL"	VARCHAR2(50)		NOT NULL
);

ALTER TABLE "MOVIE" ADD CONSTRAINT "PK_MOVIE" PRIMARY KEY (
	"MOVIE_ID"
);

ALTER TABLE "ACTOR" ADD CONSTRAINT "PK_ACTOR" PRIMARY KEY (
	"ACTOR_ID"
);

ALTER TABLE "DIRECTOR" ADD CONSTRAINT "PK_DIRECTOR" PRIMARY KEY (
	"DIRECTOR_ID"
);

ALTER TABLE "GENRE_LIST" ADD CONSTRAINT "PK_GENRE_LIST" PRIMARY KEY (
	"GENRE_ID",
	"MOVIE_ID"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "PK_MEMBER" PRIMARY KEY (
	"EMAIL"
);

ALTER TABLE "REVIEW" ADD CONSTRAINT "PK_REVIEW" PRIMARY KEY (
	"REVIEW_ID"
);

ALTER TABLE "PREFERENCE" ADD CONSTRAINT "PK_PREFERENCE" PRIMARY KEY (
	"EMAIL",
	"GENRE_ID"
);

ALTER TABLE "DIRECTED_MOVIE" ADD CONSTRAINT "PK_DIRECTED_MOVIE" PRIMARY KEY (
	"DIRECTOR_ID",
	"MOVIE_ID"
);

ALTER TABLE "ACTOR_LIST" ADD CONSTRAINT "PK_ACTOR_LIST" PRIMARY KEY (
	"ACTOR_ID",
	"MOVIE_CD"
);

ALTER TABLE "AGE_GROUP" ADD CONSTRAINT "PK_AGE_GROUP" PRIMARY KEY (
	"AGE_GROUP"
);

ALTER TABLE "GENRE" ADD CONSTRAINT "PK_GENRE" PRIMARY KEY (
	"GENRE_ID"
);

ALTER TABLE "GENRE_LIST" ADD CONSTRAINT "FK_GENRE_TO_GENRE_LIST_1" FOREIGN KEY (
	"GENRE_ID"
)
REFERENCES "GENRE" (
	"GENRE_ID"
);

ALTER TABLE "GENRE_LIST" ADD CONSTRAINT "FK_MOVIE_TO_GENRE_LIST_1" FOREIGN KEY (
	"MOVIE_ID"
)
REFERENCES "MOVIE" (
	"MOVIE_ID"
);

ALTER TABLE "MEMBER" ADD CONSTRAINT "FK_AGE_GROUP_TO_MEMBER_1" FOREIGN KEY (
	"AGE_GROUP"
)
REFERENCES "AGE_GROUP" (
	"AGE_GROUP"
);

ALTER TABLE "REVIEW" ADD CONSTRAINT "FK_MOVIE_TO_REVIEW_1" FOREIGN KEY (
	"MOVIE_CD"
)
REFERENCES "MOVIE" (
	"MOVIE_ID"
);

ALTER TABLE "REVIEW" ADD CONSTRAINT "FK_MEMBER_TO_REVIEW_1" FOREIGN KEY (
	"EMAIL"
)
REFERENCES "MEMBER" (
	"EMAIL"
);

ALTER TABLE "LIKE" ADD CONSTRAINT "FK_REVIEW_TO_LIKE_1" FOREIGN KEY (
	"REVIEW_ID"
)
REFERENCES "REVIEW" (
	"REVIEW_ID"
);

ALTER TABLE "LIKE" ADD CONSTRAINT "FK_MEMBER_TO_LIKE_1" FOREIGN KEY (
	"EMAIL"
)
REFERENCES "MEMBER" (
	"EMAIL"
);

ALTER TABLE "PREFERENCE" ADD CONSTRAINT "FK_MEMBER_TO_PREFERENCE_1" FOREIGN KEY (
	"EMAIL"
)
REFERENCES "MEMBER" (
	"EMAIL"
);

ALTER TABLE "PREFERENCE" ADD CONSTRAINT "FK_GENRE_TO_PREFERENCE_1" FOREIGN KEY (
	"GENRE_ID"
)
REFERENCES "GENRE" (
	"GENRE_ID"
);

ALTER TABLE "DIRECTED_MOVIE" ADD CONSTRAINT "FK_DIRECTOR_TO_DIRECTED_MOVIE_1" FOREIGN KEY (
	"DIRECTOR_ID"
)
REFERENCES "DIRECTOR" (
	"DIRECTOR_ID"
);

ALTER TABLE "DIRECTED_MOVIE" ADD CONSTRAINT "FK_MOVIE_TO_DIRECTED_MOVIE_1" FOREIGN KEY (
	"MOVIE_ID"
)
REFERENCES "MOVIE" (
	"MOVIE_ID"
);

ALTER TABLE "ACTOR_LIST" ADD CONSTRAINT "FK_ACTOR_TO_ACTOR_LIST_1" FOREIGN KEY (
	"ACTOR_ID"
)
REFERENCES "ACTOR" (
	"ACTOR_ID"
);

ALTER TABLE "ACTOR_LIST" ADD CONSTRAINT "FK_MOVIE_TO_ACTOR_LIST_1" FOREIGN KEY (
	"MOVIE_CD"
)
REFERENCES "MOVIE" (
	"MOVIE_ID"
);

--MOVIE
INSERT INTO MOVIE (MOVIE_ID, TITLE, OPENING_YEAR, POSTER)
VALUES (200801, '듄', SYSDATE, '듄포스터');
INSERT INTO TB_GRADE (MOVIE_ID, TITLE, OPENING_YEAR, POSTER)
VALUES (200802, '엘리멘탈', SYSDATE, '엘리멘탈포스터');